### ISSUE TITLE
Suggestion: right click function/option

### ISSUE THREAD

**Issue by circularsprojects** [Pix3lPirat3/mineflayer-autoclicker#1]
The idea's in the title. You could "autoclick" right click by just checking for a block in front of the bot, and attempting to interact with it.

**Comment by Pix3lPirat3** [comment]
This is a planned feature. I’ve used that myself for an anti-afk bot, since a server I played on didn’t detect jumping as not-afk, but right clicking a block would make you non-afk.

Thank you for your recommendation! Please let me know if you have any others. I am in the PrismarineJS discord if you ever want to message me.
